services:
  db:
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: invoiceks
      POSTGRES_USER: invoiceks
      POSTGRES_PASSWORD: invoiceks
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.keystone/postgres:/var/lib/postgresql/data
    networks:
      invoiceks:
        aliases:
          - invoiceks-db

  admin:
    build:
      dockerfile: Dockerfile.admin
      args:
        DB_PROVIDER: "postgresql"
    environment:
      KS_PORT: "3000"
      DATABASE_URL: "postgresql://invoiceks:invoiceks@db:5432/invoiceks"
      NEXT_PUBLIC_GRAPHQL_PATH: "/api/graphql"
      NEXT_PUBLIC_SERVER_URL: "http://localhost:3000"
    ports:
      - 3000:3000
    networks:
      invoiceks:
      nginx-proxy:
        aliases:
          - invoiceks

networks:
  invoiceks:
  nginx-proxy:
